"""
cf/data_prep.py
───────────────
Data preparation utilities for Collaborative Filtering.

Key responsibilities:
  - Load CF-specific LOO split (built from RAW_interactions by build_split.py)
  - Exclude rating=0 interactions (ambiguous implicit signal)
  - Build sparse user-item matrices for model training
  - Prepare Leave-One-Out (LOO) evaluation data
      → 1 ground-truth item per user (most recent from test split)
      → 99 randomly sampled negative items not in user's full history

IMPORTANT: Use load_cf_splits() (not load_splits()) for CF training.
  The original interactions_train/val/test.csv splits have 100% item
  disjointness between train and test -- items in test were never seen
  in training, making CF models score them as 0 (random-level performance).
  load_cf_splits() uses the properly-built LOO split from build_split.py.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Optional, Set

import numpy as np
import pandas as pd
import scipy.sparse as sp

# ── Paths ──────────────────────────────────────────────────────────────────────
DATA_DIR = Path(__file__).parent.parent


# ══════════════════════════════════════════════════════════════════════════════
# 1. Loading
# ══════════════════════════════════════════════════════════════════════════════

def load_splits(exclude_rating_zero: bool = True) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    [DEPRECATED FOR CF] Load pre-existing train / validation / test splits.

    WARNING: These splits have 100% item disjointness between train and test.
    Use load_cf_splits() instead for Collaborative Filtering.

    Columns: [user_id, recipe_id, date, rating, u, i]
    """
    train = pd.read_csv(DATA_DIR / "interactions_train.csv")
    val   = pd.read_csv(DATA_DIR / "interactions_validation.csv")
    test  = pd.read_csv(DATA_DIR / "interactions_test.csv")

    if exclude_rating_zero:
        before = (len(train), len(val), len(test))
        train = train[train["rating"] > 0].reset_index(drop=True)
        val   = val[val["rating"] > 0].reset_index(drop=True)
        test  = test[test["rating"] > 0].reset_index(drop=True)
        after = (len(train), len(val), len(test))
        print(
            f"[data_prep] Excluded rating=0 -- "
            f"Train: {before[0]:,}->{after[0]:,}  "
            f"Val: {before[1]:,}->{after[1]:,}  "
            f"Test: {before[2]:,}->{after[2]:,}"
        )
    else:
        print(f"[data_prep] Loaded -- Train: {len(train):,}  Val: {len(val):,}  Test: {len(test):,}")

    return train, val, test


def load_cf_splits() -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Load the properly-built CF LOO split from cf/outputs/cf_split/.

    These splits are generated by cf/build_split.py from RAW_interactions.csv
    using iterative co-filtering + temporal LOO split, ensuring:
      - All rating=0 already excluded (filtered in build_split.py)
      - 99.8%+ of test items exist in training set
      - Each user has exactly 1 item in val and 1 in test

    Columns: [user_id, recipe_id, date, rating, u, i]
      - u : integer user index (0-based)
      - i : integer item index (0-based)

    Returns
    -------
    train_df, val_df, test_df : pd.DataFrame

    Raises
    ------
    FileNotFoundError if build_split.py has not been run yet.
    """
    split_dir = DATA_DIR / "cf" / "outputs" / "cf_split"
    if not (split_dir / "cf_train.csv").exists():
        raise FileNotFoundError(
            f"CF split not found at {split_dir}. "
            "Run `python -m cf.build_split` first."
        )

    train = pd.read_csv(split_dir / "cf_train.csv")
    val   = pd.read_csv(split_dir / "cf_val.csv")
    test  = pd.read_csv(split_dir / "cf_test.csv")

    print(
        f"[data_prep] CF LOO split loaded -- "
        f"Train: {len(train):,}  Val: {len(val):,}  Test: {len(test):,}"
    )
    return train, val, test


def get_matrix_dims(*dfs: pd.DataFrame) -> tuple[int, int]:
    """
    Compute (n_users, n_items) from the union of all provided DataFrames.
    Uses columns 'u' (user index) and 'i' (item index).
    """
    all_u = pd.concat([df["u"] for df in dfs])
    all_i = pd.concat([df["i"] for df in dfs])
    n_users = int(all_u.max()) + 1
    n_items = int(all_i.max()) + 1
    print(f"[data_prep] Matrix dims -- Users: {n_users:,}  Items: {n_items:,}")
    return n_users, n_items


# ══════════════════════════════════════════════════════════════════════════════
# 2. Sparse matrix builders
# ══════════════════════════════════════════════════════════════════════════════

def build_user_item_matrix(
    df: pd.DataFrame,
    n_users: int,
    n_items: int,
    binary: bool = True,
) -> sp.csr_matrix:
    """
    Build a (n_users × n_items) sparse CSR matrix.

    Parameters
    ----------
    df     : DataFrame with columns 'u', 'i', and optionally 'rating'.
    binary : If True, all non-zero values are set to 1.
             If False, the raw rating value is used as weight.
    """
    users = df["u"].values.astype(np.int32)
    items = df["i"].values.astype(np.int32)
    data  = np.ones(len(df), dtype=np.float32) if binary else df["rating"].values.astype(np.float32)

    mat = sp.csr_matrix((data, (users, items)), shape=(n_users, n_items), dtype=np.float32)
    mat.sum_duplicates()  # merge duplicate (u, i) entries by summing
    mat.data = np.clip(mat.data, 0, 1) if binary else mat.data  # keep binary clean
    return mat


# ══════════════════════════════════════════════════════════════════════════════
# 3. History tracking
# ══════════════════════════════════════════════════════════════════════════════

def build_user_history(*dfs: pd.DataFrame) -> Dict[int, Set[int]]:
    """
    Build a mapping {u → set(items)} from one or more DataFrames.
    Used to exclude known items when sampling negatives.
    """
    history: Dict[int, Set[int]] = {}
    for df in dfs:
        for u, group in df.groupby("u")["i"]:
            if u not in history:
                history[u] = set()
            history[u].update(group.values.tolist())
    return history


# ══════════════════════════════════════════════════════════════════════════════
# 4. Leave-One-Out evaluation preparation
# ══════════════════════════════════════════════════════════════════════════════

def prepare_loo_eval(
    test_df: pd.DataFrame,
    user_history: Dict[int, Set[int]],
    n_items: int,
    n_negatives: int = 99,
    seed: int = 42,
) -> List[dict]:
    """
    Prepare Leave-One-Out (LOO) evaluation set.

    For each user in *test_df*:
      1. Select the most recent interaction as the ground-truth positive.
      2. Sample *n_negatives* items not in the user's full training history.
      3. Build a candidate list [pos + negatives], shuffled.

    Returns
    -------
    List of dicts with keys:
        u          : user index
        pos_item   : ground-truth item index
        candidates : np.ndarray of shape (1 + n_negatives,) — shuffled item indices
        label_idx  : position of pos_item inside *candidates*
    """
    rng = np.random.default_rng(seed)
    all_items = np.arange(n_items, dtype=np.int32)

    # Pick one test item per user: last by date (most recent)
    if "date" in test_df.columns:
        test_sorted = test_df.sort_values("date", ascending=True)
    else:
        test_sorted = test_df

    test_loo = (
        test_sorted
        .groupby("u", sort=False)
        .last()
        .reset_index()[["u", "i"]]
        .rename(columns={"i": "pos_item"})
    )
    print(f"[data_prep] LOO users for evaluation: {len(test_loo):,}")

    results: List[dict] = []
    skipped = 0

    for row in test_loo.itertuples(index=False):
        u        = int(row.u)
        pos_item = int(row.pos_item)

        # Everything user has seen (train [+val]) + the positive test item
        hist: Set[int] = user_history.get(u, set())
        excluded = hist | {pos_item}

        # Build boolean mask to find valid negative pool
        mask = np.ones(n_items, dtype=bool)
        for itm in excluded:
            if 0 <= itm < n_items:
                mask[itm] = False
        valid_pool = all_items[mask]

        if len(valid_pool) == 0:
            skipped += 1
            continue

        n_neg = min(n_negatives, len(valid_pool))
        neg_items = rng.choice(valid_pool, size=n_neg, replace=False)

        # Combine & shuffle
        candidates = np.concatenate([[pos_item], neg_items]).astype(np.int32)
        rng.shuffle(candidates)
        label_idx = int(np.where(candidates == pos_item)[0][0])

        results.append(
            {
                "u"         : u,
                "pos_item"  : pos_item,
                "candidates": candidates,
                "label_idx" : label_idx,
            }
        )

    if skipped:
        print(f"[data_prep] Warning: skipped {skipped} users (no valid negative pool)")
    print(f"[data_prep] LOO eval records ready: {len(results):,}")
    return results
